language: go
env:
  - BUILD_VERSION=travis-CI
before_install:
  - sudo add-apt-repository -y ppa:ethereum/ethereum
  - sudo apt-get update
  - sudo apt-get install --allow-unauthenticated -y solc
after_success:
  - bash <(curl -s https://codecov.io/bash)
go:
  - "1.11.x"

